name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet test --verbosity normal

      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: dotnet publish Client/Client.csproj -c Release

      - name: Upload Client publish output
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: client-publish
          path: Client/bin/Release/net9.0/publish/

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      # url: https://${{ secrets.VPS_HOST }} # Optional: adds link in UI
    steps:
      - uses: actions/checkout@v4

      - name: Download Client publish output
        uses: actions/download-artifact@v4
        with:
          name: client-publish
          path: ClientPublish

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Stop service on VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'sudo systemctl stop EurekaTracker.service'

      # Deploy Client
      - name: Deploy Client to VPS
        run: |
          scp -r ClientPublish/* ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/eureka-website/

      - name: Start service on VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'sudo systemctl daemon-reload || true && sudo systemctl start EurekaTracker.service && sudo systemctl is-active --quiet EurekaTracker.service'